### ISSUE TITLE
Content Organisation (Best Practices)

### ISSUE THREAD

**Issue by RichardKnop** [alphagov/tsuru-ansible#104]
Hello,

Currently this repository is just a bunch of yml files in the root directory. I suggest we should spend some time refactoring it according to Ansible best practices:
- http://docs.ansible.com/playbooks_best_practices.html

Take a look at this example repository to see how Ansible should look:
- https://github.com/ansible/ansible-examples

We should start by trying to get a proper directory structure and splitting our configuration files to modules with roles and playbooks.

This would make it easier to maintain in the future.

**Comment by brettansley** [comment]
Hi Richard

I have raised a story in Pivotal to cover this so that we can prioritise alongside our other backlog items.

https://www.pivotaltracker.com/story/show/98369602

Brett

**Comment by dcarley** [comment]
Thanks, Brett.

Richard, I'm going to close this issue. We can continue the conversation over in Pivotal.
